packages:
- '.'
- location:
    git: https://github.com/haskell-distributed/distributed-process.git
    commit: 8aa1f702b07b55da3a0a615ea95419e5ef059da8

- location:
    git: https://github.com/haskell-distributed/distributed-process-async.git
    commit: 2f2978016b6ae9cb35d4cef5a74d476b8bfedb1f

- location:
    git: https://github.com/haskell-distributed/distributed-process-extras.git
    commit: 0a79d2e5c72333e2c6ada65adfc4608ed07bf703

- location:
    git: https://github.com/haskell-distributed/distributed-process-client-server.git
    commit: 1df389a47ba0148fe9ba0718f5026eb92b84f32e

- location:
    git: https://github.com/haskell-distributed/distributed-process-simplelocalnet.git
    commit: 19e8948409c84ad52fb9678a91d38238fc29b1c8

- location:
    git: https://github.com/haskell-distributed/distributed-static.git
    commit: 16276bd2fc8a5d87d79737750b23152d58b7c1dd

- location:
    git: https://github.com/haskell-distributed/network-transport.git
    commit: 65252abe650edd3b0d45b968ace689c913d669f4

- location:
    git: https://github.com/haskell-distributed/network-transport-tcp.git
    commit: f0f2edbdfd6a5c991614984c3007dd66805cd004

- location:
    git: https://github.com/haskell-distributed/rank1dynamic.git
    commit: 323a3b2e61163754785fabda7f3e39cdaeb01863

- location:
    git: https://github.com/haskell-distributed/network-transport-inmemory.git
    commit: aece7d0754e53e321aa80bac5f2c2284a1790d73

extra-deps: []

resolver: nightly-2015-06-12
